title:       "Operating Systems 2021-1 (OS211)"
version:     "0090---23-May-2021"
copyright:   "2021-2021"
description: >- 
  This Is How Me Do It!
  This Is How Me Do It!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Anis Farhan"
address:          "Pati"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://anisfarhan.github.io/os211/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/anisfarhan/os211/"
urlghpage:        "https://anisfarhan.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]

